export const USERPROFILE_UPDATE_EDITING_LOGIN = 'USERPROFILE_UPDATE_EDITING_LOGIN';
export type USERPROFILE_UPDATE_EDITING_LOGIN = typeof USERPROFILE_UPDATE_EDITING_LOGIN;

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export type AUTHENTICATE_REQUEST = typeof AUTHENTICATE_REQUEST;

export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export type AUTHENTICATE_SUCCESS = typeof AUTHENTICATE_SUCCESS;

export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export type AUTHENTICATE_ERROR = typeof AUTHENTICATE_ERROR;






