export const USERPROFILE_UPDATE_EDITING_LOGIN = 'USERPROFILE_UPDATE_EDITING_LOGIN';
export type USERPROFILE_UPDATE_EDITING_LOGIN = typeof USERPROFILE_UPDATE_EDITING_LOGIN;

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export type LOGIN_FAILURE = typeof LOGIN_FAILURE;

export const USERPROFILE_PERFORM_LOGIN = 'USERPROFILE_PERFORM_LOGIN';
export type USERPROFILE_PERFORM_LOGIN = typeof USERPROFILE_PERFORM_LOGIN;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS;

export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export type LOAD_USER_PROFILE = typeof LOAD_USER_PROFILE;





